version: '3'

services:
  consul:
    image: "consul:1.9"
    ports:
      - "8500:8500"

  # https://grafana.com/docs/grafana-cloud/quickstart/docker-compose-linux/
  prometheus:
    image: "prom/prometheus-linux-arm64"
    ports:
      - "9090:9090"
    volumes:
      - './exporter_config.yml:/etc/prometheus/prometheus.yml'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    # to enable this container to access the host
    # 'host.docker.internal' can be named anything
    extra_hosts:
      - "host.docker.internal:host-gateway"

  node_exporter:
    image: "prom/node-exporter-linux-arm64"
    ports:
      - "9100:9100"

  grafana:
      image: grafana/grafana:7.5.7
      ports:
        - 3000:3000
      depends_on:
        - prometheus
      restart: always
      volumes:
        - ./prometheus_ds.yml:/etc/grafana/provisioning/datasources/prometheus_ds.yml
        