global:
  scrape_interval: 10s

scrape_configs:
  - job_name: node exporter
    # metrics_path: /metrics # this is the default
    static_configs:
      - targets: ["node_exporter:9100", "10.10.10.12:9100"]

  # running a python script which serves the metrics under localhost:8000 on the host machine
  - job_name: custom metrics provided by pythoh script
    metrics_path: /
    static_configs:
      - targets: ["host.docker.internal:8000"]
