global:
  scrape_interval: 10s

scrape_configs:
  - job_name: node exporter
    # this is the default
    # metrics_path: /metrics
    static_configs:
      # one node_exporter is running on a different container on the same host as the prometheus: node_exporter:9100
      # the other exporter runs on vm2: 10.10.10.12:9100
      - targets: ["node_exporter:9100", "10.10.10.12:9100"]

  # running a python script which serves the metrics under localhost:8000 on the host machine
  - job_name: custom Varnish metrics provided by a pythoh script
    metrics_path: /
    static_configs:
      - targets: ["host.docker.internal:8000"]

  - job_name: varnish exporter
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:9131"]
