---

- name: Create a directory if it does not exist
  file:
    path: /etc/demo_app
    state: directory
    mode: '0755'

- name: Copy app jar file
  copy:
    src: varnish-demo-app-0.0.1-SNAPSHOT.jar
    dest: /etc/demo_app/varnish-demo-app.jar
  notify:
    - restart demo_app
  tags:
    - backend_deployment

# TODO - stop if service exists etc.

- name: "Create systemd file"
  template:
    src: etc/systemd/system/demo_app.service.j2
    dest: /etc/systemd/system/demo_app.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - reload demo_app
  tags:
    - backend_deployment
