---


- name: Install base packages
  package:
    name: "{{ base_packages }}"
    state: present
    update_cache: true

- name: Ensure Varnish is installed.
  yum:
    name: "{{ varnish_package_name }}"
    state: present
  notify:
    - enabled varnish
    - started varnish