Vagrant.configure("2") do |config|
  config.vm.box = "spox/ubuntu-arm"
  config.vm.box_version = "1.0.0"

  # config.vm.network :forwarded_port, id: "nginx", host: 8061, guest: 80
  # config.vm.network :forwarded_port, id: "consul", host: 8501, guest: 8500
end

# Other ubuntu arm boxes:
#  - https://app.vagrantup.com/bento/boxes/ubuntu-20.04-arm64

# Vagrant.configure("2") do |config|
#   config.vm.box = "bento/ubuntu-20.04-arm64"
#   config.vm.box_version = "202112.19.0"
# end

# Works as well but pulls the arm64 version.
# Vagrant.configure("2") do |config|
#   config.vm.box = "bento/ubuntu-20.04"
# end