{
 "title": "VM",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Amount of memory in bytes currently used (jvm_memory_bytes_used, area=heap+non_heap)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used) without (area)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Maximum amount of memory in bytes that can be used (jvm_memory_bytes_max, area=heap+non_heap)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_max) without (area)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Time spent in garbage collection in ms (jvm_gc_collection_seconds, gc_type=$gc_type)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "repeat": "gc_type",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum[1m])*1000",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Avg. interval in ms between garbage collections (jvm.gc.interval_ms, gc_type=$gc_type)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "repeat": "gc_type",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "$tag_host",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "rate(jvm_gc_collection_seconds_sum[1m])*1000",
     "filters": [
      {
       "filter": "$gc_type",
       "groupBy": false,
       "tagk": "gc_type",
       "type": "literal_or"
      },
      {
       "filter": "$env",
       "groupBy": false,
       "tagk": "env",
       "type": "literal_or"
      },
      {
       "filter": ".*-.*-(${type})-\\d+.*",
       "groupBy": true,
       "tagk": "host",
       "type": "regexp"
      }
     ],
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Garbage collection rate (jvm_gc_collection_seconds_count, gc_type=$gc_type)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "repeat": "gc_type",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_count[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "jvm_memory_pool_bytes_used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (pool) (jvm_memory_pool_bytes_used)",
     "legendFormat": "{{ name }} {{ pool }}"
    }
   ]
  }
 ]
}