{
 "title": "Java Info",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Threads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "jvm_threads_current", "legendFormat": "current threads" },
    {
     "expr": "jvm_threads_state{state=\"RUNNABLE\"}",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "jvm_threads_state{state=\"WAITING\"}",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "jvm_threads_state{state=\"TIMED_WAITING\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Thread Peak",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "jvm_threads_peak", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Runnable Threads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "jvm_threads_state{state=\"RUNNABLE\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Runnable Threads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "jvm_threads_state{state=\"WAITING\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}