---
base_packages:
  - net-tools
  - screen
  - unzip

# TODO - is version 6.5 unsupported?
# This page: https://www.varnish-software.com/developers/tutorials/varnish-versions/ does not say anything about 6.5
# also this page: http://varnish-cache.org/releases/ says 6.5 is not supported anymore
varnish_package_version: "6.5"
varnish_modules_package_name: ""

# see also: https://github.com/geerlingguy/ansible-role-varnish

# Only used on Debian / Ubuntu.
varnish_apt_repo: deb https://packagecloud.io/varnishcache/varnish60lts/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} main

# ansible_distribution: ubuntu
# ansible_distribution_release: focal
# these values can also be found with: `cat /etc/os-release`
