name: Call Reusable Workflow

on:
  workflow_dispatch:

jobs:

  echo:
    runs-on: ["ubuntu-latest"]
    steps:
      - name: Print workflow URL
        run: |
          echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs/${{ github.job }}"

  call:
    uses: ./.github/workflows/reusable.yaml
    with:
      arg1: 123
