
name: Multi Job with env

on:
  workflow_dispatch:

jobs:

  one:
    runs-on: ubuntu-latest
    steps:
      - name: step
        run: | 
          echo "Setting the env var"
          echo "MY_ENV_VAR=works!" >> $GITHUB_ENV
          
  two:
    runs-on: ubuntu-latest
    needs: one
    steps:
      - name: step
        run: | 
          echo "env var: $MY_ENV_VAR"
