name: Multi Job - Testing order and dependencies

on:
  workflow_dispatch:

jobs:

  one:
    runs-on: ubuntu-latest
    steps:
      - name: step
        run: | 
          echo "1" && sleep 2
          
  two:
    runs-on: ubuntu-latest
    needs: one
    steps:
      - name: step
        run: | 
          echo "2" && sleep 2
          
  three:
    runs-on: ubuntu-latest
    needs: two
    steps:
      - name: step
        run: | 
          echo "3" && sleep 2
          
  four:
    runs-on: ubuntu-latest
    needs: three
    steps:
      - name: step
        run: | 
          echo "4"
