name: Multi Job - Testing order and dependencies

on:
  workflow_dispatch:
    inputs:
        runMonitorTest:
          required: true
          type: boolean

jobs:

  one:
    runs-on: ubuntu-latest
    steps:
      - name: step
        run: | 
          echo "1" && sleep 2 && exit 1
          
  two:
    runs-on: ubuntu-latest
    needs: one
    steps:
      - name: step
        run: | 
          echo "2" && sleep 2
          
  run-monitor-job:
    runs-on: ubuntu-latest
    needs: two
    if: inputs.runMonitorTest
    steps:
      - name: step
        run: | 
          echo "3" && sleep 2
          
  run-load-test:
    runs-on: ubuntu-latest
    needs: run-monitor-job
    if: ${{ always() && jobs.run-monitor-job.result == 'skipped' }}
    steps:
      - name: step
        run: | 
          echo "4"
