name: Allow only one workflow to run at one time

on:
  workflow_dispatch:

concurrency: somestring

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    
    - name: Sleeping
      run: |
        sleep 20

    

