name: Reusable
on:
  workflow_call:
    inputs:
      arg1:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      input1:
        description: >-
          input1:
          a test input field
        required: true

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Print
      run: | 
        echo "arg1: ${{ inputs.arg1 }} "
        sleep 5
        
    - name: Print 2
      run: | 
        echo "arg1: ${{ github.event.inputs.input1 }} "
        sleep 5
