name: Reusable
on:
  workflow_call:
    inputs:
      arg1:
        required: true
        type: string
      arg2:
        required: false
        type: string
        default: "ARG_2_DEFAULT"

  workflow_dispatch:
    inputs:
      input1:
        description: >-
          input1:
          a test input field
        required: true
      argDefault:
        required: false
        type: string
        default: "DEFAULT_WORKS"
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Print
      run: | 
        echo "arg1: ${{ inputs.arg1 }}"
        echo "argDefault: ${{ inputs.argDefault }}"
        echo "arg2: ${{ inputs.arg2 }}"
        sleep 5
        
    - name: Print 2
      run: | 
        echo "arg1: ${{ github.event.inputs.input1 }} "
        sleep 5
