name: Testing stuff

on:
  workflow_dispatch:
    inputs:
      input1:
        description: >-
          input1:
          a test input field
        required: true

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
      with:
        path: test

    - run: cat ./test/.github/scripts/myfile.txt
    
    - run: sed -ie 's/text./--text-${{ github.event.inputs.input1 }}-...-/g' ./test/.github/scripts/myfile.txt

    - run: cat ./test/.github/scripts/myfile.txt
    
    - name: replace
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.input1 != ''
      run: echo "EMPTY 1"

    - name: test 
      run: echo "${{ github.event_name == 'workflow_dispatch' && github.event.inputs.input1 == '' && "EMPTY 2" || format('Not empty:\ {0}', github.event.inputs.input1) }}"
