name: Testing stuff

on:
  # adds a "run workflow" button to the page
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
      with:
        path: test

    - run: cat ./test/.github/scripts/myfile.txt
    
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        include: "./test/.github/scripts/myfile.txt"
        find: "text."
        replace: "--text...--"
        regex: false

    - run: cat ./test/.github/scripts/myfile.txt