name: Testing stuff

on:
  workflow_dispatch:
    inputs:
      input1:
        description: >-
          input1:
          a test input field
        required: true
      enableDeployment:
        type: boolean
      env:
        description: Choose the environment
        default: test 
        type: choice
        options:
        - dev
        - test
        - prod 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Setting global variables
      uses: actions/github-script@v6
      id: var
      with:
        script: |
          core.exportVariable('ENV_VAR', core.getInput('input1', { trimWhitespace: false }));
    
    - run: echo "env variable -> ${{ env.ENV_VAR }}"
    
    - run: |
        if [ '${{ github.event.inputs.enableDeployment }}' == 'true' ]; then
          echo "includeConsole: TRUE"
        fi
        if [ '${{ github.event.inputs.enableDeployment }}' == 'false' ]; then
          echo "includeConsole: FALSE"
        fi
        if [ '${{ github.event.inputs.enableDeployment }}' == '' ]; then
          echo "includeConsole: EMPTY"
        fi
    
    - uses: actions/checkout@v3
      with:
        path: test

    - run: echo "environment selected -> ${{ github.event.inputs.env }}"

    - run: cat ./test/.github/scripts/myfile.txt
    
    - run: sed -ie 's/text./--text-${{ github.event.inputs.input1 }}-...-/g' ./test/.github/scripts/myfile.txt

    - run: cat ./test/.github/scripts/myfile.txt
    
    - if: github.event_name == 'workflow_dispatch' && github.event.inputs.input1 == ''
      run: echo "input1 is empty"

    - name: test 
      run: echo "${{ github.event_name == 'workflow_dispatch' && github.event.inputs.input1 == '' && 'EMPTY 2' || format('input1 is NOT empty:\ {0}', github.event.inputs.input1) }}"
