name: Testing stuff

on:
  workflow_dispatch:
    inputs:
      input1:
        description: >-
          input1:
          a test input field
        required: true
      enableDeployment:
        type: boolean
      env:
        description: Choose `the` environment
        default: test 
        type: choice
        options:
        - dev
        - test
        - prod 

jobs:

  one:
    runs-on: ubuntu-latest
    steps:
      - name: One
        run: |
          echo "ONE"
          sleep 5

  two:
    needs: one
    uses: jckleiner/ci-cd-examples/.github/workflows/reusable.yaml@master
    with:
      arg1: "WORKS..."
          
  three:
    runs-on: ubuntu-latest
    needs: two
    steps:
      - name: Three
        run: | 
          echo "THREE"
          sleep 5

  
