name: Testing stuff

on:
  workflow_dispatch:
    inputs:
      input1:
        description: >-
          input1:
          a test input field
        required: true
      env:
        description: Choose the environment
        default: 'dev' 
        type: choice
        options:
        - dev
        - test
        - prod 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
      with:
        path: test

    - run: echo "environment selected:\ ${{ github.event.inputs.env }}"

    - run: cat ./test/.github/scripts/myfile.txt
    
    - run: sed -ie 's/text./--text-${{ github.event.inputs.input1 }}-...-/g' ./test/.github/scripts/myfile.txt

    - run: cat ./test/.github/scripts/myfile.txt
    
    - if: github.event_name == 'workflow_dispatch' && github.event.inputs.input1 == ''
      run: echo "input1 is empty"

    - name: test 
      run: echo "${{ github.event_name == 'workflow_dispatch' && github.event.inputs.input1 == '' && 'EMPTY 2' || format('input1 is NOT empty:\ {0}', github.event.inputs.input1) }}"
